# Generated by Django 5.1.3 on 2024-11-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi')),
                ('chat_id', models.CharField(blank=True, max_length=221, null=True, verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Kanallar',
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=221, null=True, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stocks/', verbose_name='Rasmi')),
                ('stock_percent', models.IntegerField(blank=True, null=True, verbose_name='Chegirma foizi')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Aksiyalar',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('role', models.CharField(blank=True, choices=[('user', 'Oddiy foydalanuvchi'), ('admin', 'Admin')], default='user', max_length=100, null=True, verbose_name='Foydalanuvchi roli')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'WebPage',
                'verbose_name_plural': 'Web sahifalar',
                'db_table': 'web_page',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=221, null=True, verbose_name='Promo kod')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktivlik holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aksiyalar.stock', verbose_name='Aksiya')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aksiyalar.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'PromoCode',
                'verbose_name_plural': 'Promo Kodlar',
                'db_table': 'promocode',
            },
        ),
    ]
