# Generated by Django 5.1.3 on 2024-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi')),
                ('chat_id', models.CharField(blank=True, max_length=221, null=True, verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Kanallar',
                'db_table': 'channel',
            },
        ),
    ]
