# Generated by Django 5.1.3 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'WebPage',
                'verbose_name_plural': 'Web sahifalar',
                'db_table': 'web_page',
            },
        ),
    ]
