# Generated by Django 5.1.3 on 2024-11-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0002_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=221, null=True, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stocks/', verbose_name='Rasmi')),
                ('stock_percent', models.IntegerField(blank=True, null=True, verbose_name='Chegirma foizi')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Aksiyalar',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=221, null=True, verbose_name='Promo kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aksiyalar.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'PromoCode',
                'verbose_name_plural': 'Promo Kodlar',
                'db_table': 'promocode',
            },
        ),
    ]
