# Generated by Django 5.1.4 on 2024-12-06 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0002_alter_questionnaire_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='from chat id')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='message id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Aksiyalar',
                'db_table': 'stock',
            },
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 6, 15, 47, 54, 529472), null=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
