# Generated by Django 5.1.3 on 2024-11-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0003_stock_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.CharField(blank=True, default=True, null=True, verbose_name='Aktivlik holati'),
        ),
    ]
