# Generated by Django 5.1.3 on 2024-11-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0004_promocode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aksiyalar.stock', verbose_name='Aksiya'),
        ),
    ]
