# Generated by Django 5.1.3 on 2024-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aksiyalar', '0005_promocode_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktivlik holati'),
        ),
    ]
